<?php 
echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/photos.css');
echo $this->headScript()->appendFile($this->baseUrl().'/js/album.js', 'text/javascript')
                   ->appendScript($onloadScript);
?>

<div class="album_title">
	<b>Альбом: <?php echo $this->album_name;?></b>
	<?php echo " | ";?>
	<a href="<?php echo $this->url(array('controller' => 'photos', 'action' => 'add', 'id' => null)) ?>">Добавить фотографию</a>
</div>

<div class="album">
<?php foreach($this->photos as $photo) : ?>
<div class ="photo">
	<div class="top">
		<a href="<?php echo $this->url(array('controller' => 'photos', 'action' => 'show', 'id' => $photo->id)) ?>">
			<?php echo $this->escape($photo->filename);?></a>
		<?php echo " | ";?>
		<a href="<?php echo $this->url(array('controller' => 'photos', 'action' => 'delete', 'id' => $photo->id)) ?>">Удалить</a><br />
	</div>
	<div class="border">	
		<a href="<?php echo $this->url(array('controller' => 'photos', 'action' => 'show', 'id' => $photo->id)) ?>">
			<img src="<?php echo $this->baseUrl();?>/images/<?php echo $photo->filename;?>" onload = "resize(this)"/>
		</a>
	</div>
	
	<div class="bottom">
		Заголовок: <?php echo $this->escape($photo->title);?><br/>
		Адрес фото: <?php echo $this->escape($photo->address_photo);?>
	</div>
</div>
</div>
<?php endforeach; ?>