<?php
	$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=windows-1251');
	$this->headTitle()->setSeparator(' — ');
	$this->headTitle('Photo Gallery');
	echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/all_pages.css'); ?>
</head>
<body>
<div id="site">
	<div id="top">
		Photo Gallery
	</div>
	<div id="content">
        <?php //if(Account::checkAccess()): ?>
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'id' => null, 'album_id' => null)) ?>">To Home</a>
        <?php //endif;?>
	<h1><?php echo $this->escape($this->title); ?></h1>
	<?php echo $this->layout()->content; ?>
	</div>
</div>
</body>
</html>